# Generated by Django 5.0.3 on 2024-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='heading',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
